version: '3.1'

services:
  mysql-database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: guiapress
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql-database